const faqQuestions = [
  {
    question: "What is Teal Climate?",
    answer:
      "Teal Climate is a SaaS platform helping businesses and institutions measure, manage, and reduce their carbon emissions.",
  },
  {
    question: "Who can use Teal Climate?",
    answer:
      "Our platform is designed for organizations of all sizes, including those in finance, real estate, service, and manufacturing sectors.",
  },
  {
    question: "Is the platform compliant with the GHG Protocol?",
    answer:
      "Yes, our methodologies align with the Greenhouse Gas Protocol and other global standards.",
  },
  {
    question: "How can I get started?",
    answer:
      "Simply sign up for a plan that fits your needs and begin your carbon accounting journey today.",
  },
  {
    question: "Is customer support available?",
    answer:
      "Yes, our dedicated support team is available via email and we can schedule calls to further assist you in your decarbonization journey.",
  },
  {
    question: "Does Teal Climate provide API access?",
    answer:
      "Yes, we offer robust API access for Enterprise customers, enabling seamless integration with ERP systems, CRM tools, and other third-party platforms.",
  },
  {
    question: "How secure is my data on Teal Climate?",
    answer:
      "We prioritize data security and comply with global standards such as GDPR. All data is encrypted both in transit and at rest, and we conduct regular security audits to safeguard your information.",
  },
  {
    question: "Can I customize reports generated by Teal Climate?",
    answer:
      "Yes, our platform allows extensive customization of reports, including selecting specific metrics, time frames, and visualization formats. Professional and Enterprise plans include additional advanced reporting features.",
  },
  {
    question: "What data formats does Teal Climate support for data upload?",
    answer:
      "Teal Climate supports multiple formats, including CSV, Excel, and JSON. We also offer custom data-mapping tools to ensure seamless integration with your existing data.",
  },
  {
    question: "What is the uptime guarantee for the Teal Climate platform?",
    answer:
      "We ensure 99.9% uptime, backed by our high-availability infrastructure and proactive monitoring systems.",
  },
  {
    question: "Can I integrate Teal Climate with my existing systems?",
    answer:
      "Absolutely! Our API and integration support make the process seamless.",
  },
  {
    question: "Can I export my data from Teal Climate?",
    answer:
      "Yes, all data and reports can be exported in various formats, including CSV, PDF, and Excel, making it easy to share insights with stakeholders.",
  },
];

export default faqQuestions;